[book]
authors = ["MatthewSong"]
language = "en"
multilingual = false
src = "src"
title = "Covenant Mixing Guide"

[output.html]
git-repository-url = "https://github.com/LuxArgentum/covenant-mixing-guide"

[output.html.playground]
runnable = false
